import localFont from "next/font/local"
import "../assets/styles/global.scss"
import Navbar from "@/views/components/Navbar";

const bigRiver = localFont({
  src: "../assets/fonts/Big_River_Sample.woff",
  variable: "--font-bigRiver",
  display: "swap"
})

const satoshi = localFont({
  src: "../assets/fonts/Satoshi-Variable.woff2",
  variable: "--font-satoshi",
  display: "swap",
  weight: "300 900",
})

export const metadata = {
  title: "Santhosh Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${satoshi.variable} ${bigRiver.variable}`}>
      <body>
        <header>
          <Navbar />
        </header>
        <main className="padding-top">
          {children}
        </main>
      </body>
    </html>
  );
}
